### ISSUE TITLE
Merge cloud dependencies with existing Boot ones

### ISSUE THREAD

**Issue by dsyer** [dsyer/cloud-initializr#1]
When someone changes the default meta data at spring-io/initializr this one needs to be updated, but most of the changes are just copy paste which is ugly.

**Comment by snicoll** [comment]
That brings back the problem of the versionRange.

**Comment by dsyer** [comment]
Yep. See also #3.

**Comment by dsyer** [comment]
Fixed by using a (new, unmerged) customizer callback in `InitializrMetadata`: https://github.com/dsyer/cloud-initializr/blob/master/app.groovy#L22
