### ISSUE TITLE
Download link for .zip distro is not Cloud enabled

### ISSUE THREAD

**Issue by dsyer** [dsyer/cloud-initializr#2]
The default download link from spring-io/initializr is for the vanilla spring-boot CLI. The install.sh in this project takes care of adding the Cloud CLI, but we don't yet support the direct download option.

**Comment by snicoll** [comment]
That one is easy, there is a service that is responsible to create a redirect URL to the repository. We may be able to abstract that a bit more.

**Comment by dsyer** [comment]
Yeah it's easy, as long as there is actually a zip file URL to redirect to (spring cloud CLI is just a jar library).

**Comment by snicoll** [comment]
maybe it's going a bit too far? How about keeping the cli and changing the template to have an extra command to install the cloud extensions? (same thing as the curl command on the right actually)

**Comment by dsyer** [comment]
Changing which template? The home.html?

**Comment by snicoll** [comment]
yes

**Comment by dsyer** [comment]
Done (custom home.html).
