### ISSUE TITLE
Label on UI says "Spring Boot Version" when it is really "Spring Cloud Version"

### ISSUE THREAD

**Issue by dsyer** [dsyer/cloud-initializr#4]
Actually the CLI and CURL interfaces are affected too since they say "bootVersion" where really I just want it to be "version". Probably requires changes in the base metadata.

**Comment by snicoll** [comment]
See https://github.com/spring-io/initializr/issues/89 for the label. For the actual argument/request parameter I am afraid that we will have to break the meta-data format if we want to do this.

**Comment by dsyer** [comment]
Fixed via a custom home.html.

**Comment by snicoll** [comment]
Do you really intend to fix it that way or is it for the time being?

**Comment by dsyer** [comment]
I needed a fix for now. I'd rather not duplicate the home.html but I don't think I have a choice right now (plus I needed to fix #2).
